# Generated by Django 4.2.1 on 2023-06-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newPage', '0008_alter_usuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='idTipoUsuario',
            field=models.AutoField(db_column='idTipo', default=0, primary_key=True, serialize=False, verbose_name='ID_tipo_Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(db_column='idTipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='newPage.tipousuario'),
        ),
    ]
