# Generated by Django 4.2.1 on 2023-06-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newPage', '0002_alter_tipousuario_idtipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=2749, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
