# Generated by Django 4.2.1 on 2023-06-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newPage', '0003_usuario_last_login_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
