# Generated by Django 4.2.2 on 2023-06-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newPage', '0012_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
